### PR TITLE
has a 6th column that can be used to populate metadata_link attribute

### PR DESCRIPTION
**Pull request by emontgomery-usgs**

### CODE REVIEW

**Comment by kwilcox** [comment]
You need to add a column name for the "metadata_link" and fix a missing quote on line 2.

**Comment by emontgomery-usgs** [comment]
@kwilcox 

Wasn't the intent of the 6th column to point to pages like https://stellwagen.er.usgs.gov/argo_merchant.html? not just pointing to the TDS catalog?

I was trying to see if the changes in the comments above were made, and they seem to be, but am unsure of the overall staus.
Thanks!

**Comment by kwilcox** [comment]
Yup it was. I manually cleaned up your changes (there were missing quotes and a missing column header) and opened this as a replacement: #285.

**Comment by emontgomery-usgs** [comment]
@kwilcox - should we add the 6th column to the version at the link I sent (and the code I use to generate what goes on our portal)?  Seems like it would be helpful.  I thought I'd see 6 columns in the version on git-hub- but I only see 5, with the last comment being about changing the pointer to silt?  do I need to pull or update to see 6 columns  ?
Thanks!

**Comment by kwilcox** [comment]
I just merged my PR and you should see it in the code now

**Comment by emontgomery-usgs** [comment]
Thank you, I see it now.

**Pull request closed without merging**
