### PR TITLE
thredds crawler script modifications to post new datasets to sciwms and update endpoints

### PR DESCRIPTION
**Pull request by ayan-usgs**
PR for #89.

Added some new methods to facilitate the making POSTs to sciwms, and to introspect and update the WMS endpoints.

There are also methods to return layers and update the default `min` and `max` parameters. They are not currently called by the scripts.

### CODE REVIEW

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

I've given this a smoke on my end. Please review and merge at your discretion. 

Any comments or suggestions are appreciated.

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

Just wanted to make sure this PR didn't fall off the radar.

**Comment by rsignell-usgs** [comment]
@ayan-usgs, jeez, it did fall of the radar, even though I was waiting for this!
I'll check it out ASAP.  Awesome!

**Comment by rsignell-usgs** [comment]
@ayan-usgs, do you this code should this be added to the yaml2ncml repo so it can be installable?
I think that would make sense, but value your input.

**Comment by rsignell-usgs** [comment]
or maybe it's own package?

**Comment by rsignell-usgs** [comment]
Now that we've got functions, it seems it would be nice to package and install this.

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

It can certainly be moved as a package to the yaml2ncml repo. They both fall under the theme of making datasets available for the CMG Portal, or other similar application with some simple modifications. This would be appropriate with most of the modules in `catalog_harvest`. The only module I would hesitate to put into the yaml2naml repo, would be `sciwms_requests`; it's designed such that if we wanted to, we could use it as a starting point for a "sciwms configuration package", similar to https://github.com/boundlessgeo/gsconfig.

**Comment by rsignell-usgs** [comment]
So maybe micropackages are the best option?
I'm just trying to figure out how a user could "conda install" this.

**Comment by rsignell-usgs** [comment]
But for now, I guess we can run it without installing, so merging.

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

I concur, micropackages would be a clean way to break up the thematically different components, while having them easily installable. But as you said, we don't need to do that right now.

**Comment by ayan-usgs** [comment]
For reference, this breakup into micropackages seems to make sense:

* `sciwms_requests`
* `yaml2ncml`
* `iso_utils`, `sciwms_iso`, `get_ts_iso`, `get_ncml_daily_iso`, and `get_daily_iso`. There would be a dependency on `sciwms_requests`. Some work on how the log file and thredd servers are passed in would be necessary to make them more general.

**Pull request merged**
