### PR TITLE
Update get_ncml_daily_iso.py

### PR DESCRIPTION
**Pull request by alexisbeudin**

### CODE REVIEW

**Comment by alexisbeudin** [comment]
do I have to create a pull request every time I add a new catalog in the list?

**Comment by rsignell-usgs** [comment]
@alexisbeudin, do you still need catalogs added here
https://github.com/USGS-CMG/usgs-cmg-portal/blob/master/catalog_harvest/get_ncml_daily_iso.py#L12-L19
or are you all set?

If you need more catalogs, please update the PR or I can close this and you can open another.   I'll try to be better about merging quickly in the future.   If I don't , please bug me!

**Comment by alexisbeudin** [comment]
@rsignell-usgs, I am all set. Thanks!

**Comment by rsignell-usgs** [comment]
@alexisbeudin , okay, thanks.  Closing this PR then.

**Pull request closed without merging**
